#pragma once

namespace g80::console::color {
    const wchar_t *FORE_COLOR_BLACK{L"\033[30m"};
    const wchar_t *FORE_COLOR_RED{L"\033[31m"};
    const wchar_t *FORE_COLOR_GREEN{L"\033[32m"};
    const wchar_t *FORE_COLOR_YELLOW{L"\033[33m"};
    const wchar_t *FORE_COLOR_BLUE{L"\033[34m"};
    const wchar_t *FORE_COLOR_MAGENTA{L"\033[35m"};
    const wchar_t *FORE_COLOR_CYAN{L"\033[36m"};
    const wchar_t *FORE_COLOR_GREY{L"\033[37m"};
    const wchar_t *FORE_COLOR_LIGHT_RED{L"\033[91m"};
    const wchar_t *FORE_COLOR_LIGHT_GREEN{L"\033[92m"};
    const wchar_t *FORE_COLOR_LIGHT_YELLOW{L"\033[93m"};
    const wchar_t *FORE_COLOR_LIGHT_BLUE{L"\033[94m"};
    const wchar_t *FORE_COLOR_LIGHT_MAGENTA{L"\033[95m"};
    const wchar_t *FORE_COLOR_LIGHT_CYAN{L"\033[96m"};
    const wchar_t *FORE_COLOR_WHITE{L"\033[97m"};
    const wchar_t *BACK_COLOR_BLACK{L"\033[40m"};
    const wchar_t *BACK_COLOR_RED{L"\033[41m"};
    const wchar_t *BACK_COLOR_GREEN{L"\033[42m"};
    const wchar_t *BACK_COLOR_YELLOW{L"\033[43m"};
    const wchar_t *BACK_COLOR_BLUE{L"\033[44m"};
    const wchar_t *BACK_COLOR_MAGENTA{L"\033[45m"};
    const wchar_t *BACK_COLOR_CYAN{L"\033[46m"};
    const wchar_t *BACK_COLOR_GREY{L"\033[47m"};
    const wchar_t *BACK_COLOR_LIGHT_RED{L"\033[101m"};
    const wchar_t *BACK_COLOR_LIGHT_GREEN{L"\033[102m"};
    const wchar_t *BACK_COLOR_LIGHT_YELLOW{L"\033[103m"};
    const wchar_t *BACK_COLOR_LIGHT_BLUE{L"\033[104m"};
    const wchar_t *BACK_COLOR_LIGHT_MAGENTA{L"\033[105m"};
    const wchar_t *BACK_COLOR_LIGHT_CYAN{L"\033[106m"};
    const wchar_t *BACK_COLOR_WHITE{L"\033[107m"};
    const wchar_t *RESET{L"\033[0m"};
    const wchar_t *BOLD{L"\033[1m"};
    const wchar_t *UNDERLINED{L"\033[4m"};
    const wchar_t *NO_UNDERLINE{L"\033[24m"};
    const wchar_t *REVERSE_COLOR{L"\033[7m"};
    const wchar_t *NO_REVERSE_COLOR{L"\033[27m"};
}